
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 10 16:46:49 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1.sm130075d;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LCBR = 24;
  public static final int CONST = 26;
  public static final int RBR = 21;
  public static final int NUMCONST = 3;
  public static final int CONTINUE = 35;
  public static final int LSBR = 22;
  public static final int ADDOPRIGHT = 10;
  public static final int FOR = 33;
  public static final int MINUS = 8;
  public static final int STATIC = 29;
  public static final int AND = 17;
  public static final int DMINUS = 16;
  public static final int OR = 18;
  public static final int CLASS = 27;
  public static final int PLUS = 9;
  public static final int ASSIGN = 12;
  public static final int IF = 31;
  public static final int DOT = 14;
  public static final int RELOP = 11;
  public static final int EOF = 0;
  public static final int SCOLIN = 13;
  public static final int RETURN = 36;
  public static final int RCBR = 25;
  public static final int NEW = 40;
  public static final int PROGRAM = 39;
  public static final int error = 1;
  public static final int MULOPRIGHT = 7;
  public static final int BREAK = 34;
  public static final int IDENT = 2;
  public static final int VOID = 30;
  public static final int RSBR = 23;
  public static final int COLIN = 19;
  public static final int ELSE = 32;
  public static final int READ = 38;
  public static final int CHARCONST = 5;
  public static final int LBR = 20;
  public static final int BOOLCONST = 4;
  public static final int EXTENDS = 28;
  public static final int DPLUS = 15;
  public static final int PRINT = 37;
  public static final int MULOPLEFT = 6;
}

